apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.78
    path: '/srv/nfs/kubedata/pv0'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.78
    path: '/srv/nfs/kubedata/pv1'
