apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: example.com1/nfs
parameters:
  archiveOnDelete: 'false'
