apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: testcorn
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: busybox
              command: ['echo', 'Hello corn job']
          restartPolicy: Never
